function [fitresult, gof] = createFit(t, RAD51_FracCover)
%CREATEFIT(T,RAD51_FRACCOVER)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: RAD51_FracCover
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Nov-2020 06:17:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, RAD51_FracCover );

% Set up fittype and options.
ft = fittype( 'A*(1-exp(-k*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.758437651080555 0.325860752633146];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'Bounded Exponential Fit' );
% h = plot( fitresult , xData, yData);
% legend( h, 'RAD51_FracCover vs. t', 'Bounded Exponential Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 't', 'Interpreter', 'none' );
% ylabel( 'RAD51_FracCover', 'Interpreter', 'none' );



