function [fitresult, gof] = LinearEquilibrium_Test(t_Equilibrium_Test, RAD51_Equilibrium_Test)
%CREATEFIT1(T_EQUILIBRIUM_TEST,RAD51_EQUILIBRIUM_TEST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t_Equilibrium_Test
%      Y Output: RAD51_Equilibrium_Test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Jun-2021 14:35:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t_Equilibrium_Test, RAD51_Equilibrium_Test );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'RAD51_Equilibrium_Test vs. t_Equilibrium_Test', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't_Equilibrium_Test', 'Interpreter', 'none' );
% ylabel( 'RAD51_Equilibrium_Test', 'Interpreter', 'none' );
% grid on


